# Generated by Django 4.2.30 on 2026-06-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anonymize_requested',
            field=models.BooleanField(default=False, help_text='When enabled, your identity will be hidden on exported versions of your reports.', verbose_name='Request identity concealment on exported reports'),
        ),
    ]
