# Generated by Django 5.0.6 on 2026-06-15 23:51

import django.db.models.deletion
import incidents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('incident_create', 'Incident Created'), ('incident_view', 'Incident Viewed'), ('incident_export', 'Incident Exported'), ('account_delete', 'Account Deleted'), ('consent_change', 'Consent Changed'), ('failed_login', 'Failed Login'), ('password_reset', 'Password Reset'), ('admin_action', 'Admin Action')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_summary', models.TextField(blank=True)),
                ('ip_hash', models.CharField(blank=True, help_text='SHA-256 hash of IP address', max_length=64)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_category', models.CharField(choices=[('social_media', 'Social Media (WhatsApp, Twitter, Instagram, TikTok)'), ('messaging', 'Messaging (Telegram, Signal, SMS)'), ('learning', 'Learning Management (Google Classroom, Moodle, Blackboard)'), ('video_conference', 'Video Conferencing (Zoom, Google Meet, Teams)'), ('email', 'Email Services'), ('cloud_storage', 'Cloud Storage (Google Drive, OneDrive)'), ('mobile_app', 'Mobile Application'), ('website', 'Website / Portal'), ('other', 'Other Platform')], max_length=50, verbose_name='Platform or service where the violation occurred')),
                ('platform_name', models.CharField(blank=True, help_text='Specific platform name if not listed above', max_length=200)),
                ('date_of_occurrence', models.DateField(verbose_name='When did this happen?')),
                ('incident_classification', models.CharField(choices=[('unauthorized_access', 'Unauthorized Access - Someone accessed your account or device without permission'), ('doxxing', 'Doxxing - Personal information shared publicly without consent'), ('impersonation', 'Impersonation - Someone pretending to be you online'), ('nonconsensual_sharing', 'Non-Consensual Sharing - Private images or messages shared without permission'), ('cyberstalking', 'Cyberstalking - Repeated unwanted digital attention or surveillance'), ('harassment', 'Online Harassment - Abusive, threatening, or degrading messages'), ('doxxing_threat', 'Doxxing Threat - Threat to expose personal information'), ('revenge_porn', 'Non-Consensual Intimate Image Distribution'), ('phishing', 'Phishing - Fraudulent attempt to obtain your personal information'), ('account_takeover', 'Account Takeover - Someone took control of your account'), ('data_breach', 'Data Breach - Your data was exposed through a platform breach'), ('surveillance', 'Surveillance - Being monitored without knowledge or consent'), ('outing', 'Outing - Private identity or status revealed without consent'), ('other', 'Other violation not listed here')], max_length=50, verbose_name='Type of privacy violation')),
                ('narrative', models.TextField(help_text='Please describe the incident in as much detail as you feel comfortable sharing.', verbose_name='Describe what happened')),
                ('actor_involvement', models.CharField(choices=[('known_person', 'Known person (fellow student, colleague, acquaintance)'), ('known_institution', 'Known institution (university, department, organization)'), ('stranger', 'Unknown person / stranger'), ('anonymized', 'Anonymous / hidden identity'), ('intimate_partner', 'Current or former intimate partner'), ('authority_figure', 'Authority figure (lecturer, administrator, employer)'), ('group', 'Group of people'), ('other_actor', 'Other')], max_length=30, verbose_name='Who was involved?')),
                ('actor_description', models.CharField(blank=True, help_text='Optional: any additional details about the person or people involved', max_length=300)),
                ('severity_rating', models.IntegerField(choices=[(1, 'Mild - Noticeable but manageable impact'), (2, 'Moderate - Significant impact on daily life'), (3, 'Severe - Serious impact requiring support'), (4, 'Critical - Extreme impact requiring immediate assistance')], verbose_name='How severe was this incident for you?')),
                ('evidence_file', models.FileField(blank=True, help_text='Attach evidence (screenshot, document). Max 5MB. Allowed: PNG, JPEG, PDF', upload_to=incidents.models.evidence_upload_path)),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Submit anonymously (your identity will not be stored with this report)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident Report',
                'verbose_name_plural': 'Incident Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Harm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harm_category', models.CharField(choices=[('anxiety', 'Anxiety - Persistent worry or fear about digital safety'), ('humiliation', 'Humiliation - Feeling publicly shamed or degraded'), ('distress', 'Psychological Distress - Overwhelming emotional pain or upset'), ('fear_safety', 'Fear for Physical Safety - Concern for personal physical well-being'), ('loss_trust', 'Loss of Trust - Difficulty trusting others in online or offline spaces'), ('self_blame', 'Self-Blame - Feeling responsible for the violation'), ('isolation', 'Social Withdrawal - Avoiding social interactions or online spaces'), ('academic_anxiety', 'Academic Anxiety - Fear of academic repercussions from the incident'), ('ptsd_symptoms', 'Trauma Symptoms - Flashbacks, nightmares, or intrusive thoughts'), ('reputation', 'Reputation Harm - Damage to social or academic standing'), ('academic_penalty', 'Academic Penalty - Loss of grades, opportunities, or standing'), ('financial_loss', 'Financial Loss - Money lost due to the violation'), ('lost_opportunity', 'Lost Opportunity - Missed academic or professional chances'), ('social_ostracism', 'Social Ostracism - Exclusion from peer groups or communities'), ('employment_impact', 'Employment Impact - Harm to job prospects or current employment'), ('physical_safety', 'Physical Safety Threat - Real-world stalking or harm'), ('other_harm', 'Other harm not described above')], max_length=50, verbose_name='What kind of harm did you experience?')),
                ('severity_score', models.IntegerField(choices=[(1, 'Mild - Noticeable but manageable impact'), (2, 'Moderate - Significant impact on daily life'), (3, 'Severe - Serious impact requiring support'), (4, 'Critical - Extreme impact requiring immediate assistance')], verbose_name='How severe is this specific harm?')),
                ('duration', models.CharField(choices=[('one_time', 'One-time occurrence'), ('repeated_short', 'Repeated over days or weeks'), ('repeated_long', 'Recurring over months'), ('ongoing', 'Currently ongoing'), ('unknown', 'Uncertain duration')], max_length=30, verbose_name='How long has this harm lasted?')),
                ('elaboration', models.TextField(blank=True, help_text='Share anything else about how this harm affected you.', verbose_name='Additional details about this harm (optional)')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harms', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'Harm Classification',
                'verbose_name_plural': 'Harm Classifications',
            },
        ),
    ]
