# Generated by Django 4.2.30 on 2026-06-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_alter_incident_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='anonymize_requested',
            field=models.BooleanField(default=False, help_text='When enabled, your identity will be hidden in any exported version of this report.', verbose_name='Request identity concealment on exported reports'),
        ),
    ]
