# Generated by Django 4.2.30 on 2026-08-02 20:53

from django.db import migrations, models
import incidents.models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_add_incident_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='concealment_status',
            field=models.CharField(choices=[('none', 'No concealment'), ('requested', 'Concealment requested'), ('granted', 'Concealment granted'), ('revoked', 'Concealment revoked')], default='none', max_length=20, verbose_name='Identity concealment status'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='evidence_file',
            field=models.FileField(blank=True, help_text='Attach evidence (screenshot, document). Max 100KB. Allowed: PNG, JPEG, PDF', upload_to=incidents.models.evidence_upload_path),
        ),
    ]
