# Generated by Django 5.0.6 on 2026-06-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('legal', 'Legal Rights & Reporting'), ('mental_health', 'Mental Health & Wellbeing'), ('digital_safety', 'Digital Safety Guides'), ('academic_support', 'Academic Support'), ('campus_resources', 'Campus Resources'), ('emergency', 'Emergency Contacts'), ('general', 'General Guidance')], max_length=50)),
                ('description', models.TextField()),
                ('external_link', models.URLField(blank=True, help_text='Optional link to external resource')),
                ('relevance_tags', models.CharField(blank=True, help_text='Comma-separated tags for filtering', max_length=500)),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['order', 'title'],
            },
        ),
    ]
