# Generated by Django 4.2.30 on 2026-08-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone number (e.g. tel: link friendly)', max_length=100),
        ),
        migrations.AddField(
            model_name='resource',
            name='harm_categories',
            field=models.CharField(blank=True, help_text='Comma-separated harm category keys this resource addresses (e.g. anxiety, distress, physical_safety)', max_length=500),
        ),
        migrations.AddField(
            model_name='resource',
            name='incident_types',
            field=models.CharField(blank=True, help_text='Comma-separated incident classification keys this resource helps with (e.g. doxxing, cyberstalking, account_takeover)', max_length=500),
        ),
    ]
